// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUsHUkogAIV20mDZkVlI22SOAsZajuqWw',
    appId: '1:178621169809:android:eabc80ccb1853cf5743f30',
    messagingSenderId: '178621169809',
    projectId: 'hdf-stats',
    storageBucket: 'hdf-stats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFpn9v91cFLoOL2HbQLgSKPSCDBr75o-A',
    appId: '1:178621169809:ios:d6478e745bb3a024743f30',
    messagingSenderId: '178621169809',
    projectId: 'hdf-stats',
    storageBucket: 'hdf-stats.firebasestorage.app',
    iosBundleId: 'com.example.hdfStats',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSAdGhlmBru6HROVHD11VP_1AQfaCVscg',
    appId: '1:178621169809:web:5c377171334e8e11743f30',
    messagingSenderId: '178621169809',
    projectId: 'hdf-stats',
    authDomain: 'hdf-stats.firebaseapp.com',
    storageBucket: 'hdf-stats.firebasestorage.app',
    measurementId: 'G-55K354LCJT',
  );

}