/// Convierte [nationality] o país (inglés, como devuelve API-Football) a emoji de bandera.
String flagEmojiFromCountryName(String? nationalityOrCountry) {
  final iso = _iso2FromCountryName(nationalityOrCountry);
  if (iso == null || iso.length != 2) return '';
  final a = iso.toUpperCase();
  final c0 = a.codeUnitAt(0);
  final c1 = a.codeUnitAt(1);
  if (c0 < 65 || c0 > 90 || c1 < 65 || c1 > 90) return '';
  return String.fromCharCode(0x1F1E6 + c0 - 65) +
      String.fromCharCode(0x1F1E6 + c1 - 65);
}

String? _iso2FromCountryName(String? raw) {
  if (raw == null) return null;
  final k = raw.trim().toLowerCase();
  if (k.isEmpty) return null;
  return _countryNameLowerToIso2[k];
}

/// Nombres en inglés/minúsculas (API-Sports / FIFA style).
const Map<String, String> _countryNameLowerToIso2 = {
  'afghanistan': 'AF',
  'albania': 'AL',
  'algeria': 'DZ',
  'andorra': 'AD',
  'angola': 'AO',
  'argentina': 'AR',
  'armenia': 'AM',
  'australia': 'AU',
  'austria': 'AT',
  'azerbaijan': 'AZ',
  'bahrain': 'BH',
  'bangladesh': 'BD',
  'belarus': 'BY',
  'belgium': 'BE',
  'benin': 'BJ',
  'bolivia': 'BO',
  'bosnia-herzegovina': 'BA',
  'bosnia and herzegovina': 'BA',
  'brazil': 'BR',
  'bulgaria': 'BG',
  'burkina faso': 'BF',
  'burundi': 'BI',
  'cambodia': 'KH',
  'cameroon': 'CM',
  'canada': 'CA',
  'cape verde': 'CV',
  'chile': 'CL',
  'china': 'CN',
  'colombia': 'CO',
  'congo': 'CG',
  'congo dr': 'CD',
  'costa rica': 'CR',
  'croatia': 'HR',
  'cuba': 'CU',
  'cyprus': 'CY',
  'czech republic': 'CZ',
  'denmark': 'DK',
  'ecuador': 'EC',
  'egypt': 'EG',
  'el salvador': 'SV',
  'england': 'GB',
  'estonia': 'EE',
  'ethiopia': 'ET',
  'faroe islands': 'FO',
  'finland': 'FI',
  'france': 'FR',
  'gabon': 'GA',
  'gambia': 'GM',
  'georgia': 'GE',
  'germany': 'DE',
  'ghana': 'GH',
  'greece': 'GR',
  'guatemala': 'GT',
  'guinea': 'GN',
  'haiti': 'HT',
  'honduras': 'HN',
  'hong kong': 'HK',
  'hungary': 'HU',
  'iceland': 'IS',
  'india': 'IN',
  'indonesia': 'ID',
  'iran': 'IR',
  'iraq': 'IQ',
  'ireland': 'IE',
  'israel': 'IL',
  'italy': 'IT',
  'ivory coast': 'CI',
  'côte d\'ivoire': 'CI',
  "cote d'ivoire": 'CI',
  'jamaica': 'JM',
  'japan': 'JP',
  'jordan': 'JO',
  'kazakhstan': 'KZ',
  'kenya': 'KE',
  'kosovo': 'XK',
  'kuwait': 'KW',
  'latvia': 'LV',
  'lebanon': 'LB',
  'liberia': 'LR',
  'libya': 'LY',
  'liechtenstein': 'LI',
  'lithuania': 'LT',
  'luxembourg': 'LU',
  'madagascar': 'MG',
  'malawi': 'MW',
  'malaysia': 'MY',
  'mali': 'ML',
  'malta': 'MT',
  'mauritania': 'MR',
  'mauritius': 'MU',
  'mexico': 'MX',
  'moldova': 'MD',
  'montenegro': 'ME',
  'morocco': 'MA',
  'mozambique': 'MZ',
  'myanmar': 'MM',
  'namibia': 'NA',
  'netherlands': 'NL',
  'the netherlands': 'NL',
  'holland': 'NL',
  'new zealand': 'NZ',
  'nicaragua': 'NI',
  'niger': 'NE',
  'nigeria': 'NG',
  'north macedonia': 'MK',
  'macedonia': 'MK',
  'northern ireland': 'GB',
  'norway': 'NO',
  'oman': 'OM',
  'pakistan': 'PK',
  'palestine': 'PS',
  'panama': 'PA',
  'paraguay': 'PY',
  'peru': 'PE',
  'philippines': 'PH',
  'poland': 'PL',
  'portugal': 'PT',
  'puerto rico': 'PR',
  'qatar': 'QA',
  'romania': 'RO',
  'russia': 'RU',
  'rwanda': 'RW',
  'san marino': 'SM',
  'saudi arabia': 'SA',
  'scotland': 'GB',
  'senegal': 'SN',
  'serbia': 'RS',
  'seychelles': 'SC',
  'sierra leone': 'SL',
  'singapore': 'SG',
  'slovakia': 'SK',
  'slovenia': 'SI',
  'somalia': 'SO',
  'south africa': 'ZA',
  'south korea': 'KR',
  'korea republic': 'KR',
  'korea, south': 'KR',
  'spain': 'ES',
  'sudan': 'SD',
  'suriname': 'SR',
  'sweden': 'SE',
  'switzerland': 'CH',
  'syria': 'SY',
  'taiwan': 'TW',
  'tajikistan': 'TJ',
  'tanzania': 'TZ',
  'thailand': 'TH',
  'togo': 'TG',
  'trinidad and tobago': 'TT',
  'tunisia': 'TN',
  'turkey': 'TR',
  'türkiye': 'TR',
  'turkmenistan': 'TM',
  'uganda': 'UG',
  'ukraine': 'UA',
  'united arab emirates': 'AE',
  'united states': 'US',
  'usa': 'US',
  'uruguay': 'UY',
  'uzbekistan': 'UZ',
  'venezuela': 'VE',
  'vietnam': 'VN',
  'wales': 'GB',
  'yemen': 'YE',
  'zambia': 'ZM',
  'zimbabwe': 'ZW',
  'dominican republic': 'DO',
  'equatorial guinea': 'GQ',
  'guinea-bissau': 'GW',
  'south sudan': 'SS',
  'sri lanka': 'LK',
};
